config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "consultations#index"
  # root "posts#index"
  get "consultations", to: "consultations#index", as: "consultations_index"
  get "consultations/:id", to: "consultations#show", as: "consultation_show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/consultation.rb
class Consultation < ApplicationRecord
  has_one_attached :image
end

app/models/l.rb
class L < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/consultations_controller.rb
class ConsultationsController < ApplicationController
  def index
    @consultations = Consultation.all
  end

  def show
    @consultation = Consultation.find(params[:id])
  end

  def consultation_params
    params.require(:consultation).permit(:name, :address, :kontakt, :opening_hours, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/views/consultations/index.html.erb
<div class="outer-container" style="background-image: url('<%= asset_path("background_white.jpg") %>'); background-size: cover; background-position: center; padding: 80px 150;">
  <div class="inner-container" style="background-image: url('<%= asset_path("background_green.jpg") %>'); background-size: cover; background-position: center; width: 85%; height: auto; margin: 0 auto; padding: 20px;">
    <div class="flex">
      <h1>Beratungsstellen:</h1>
    </div>
    <div class="container">
      <div class="row justify-content-center">
        <% @consultations.each do |consultation|%>
          <div class="col-md-4 d-flex mb-4">
            <a href="#" class="card-link" style="text-decoration: none;">
            <div class="card" style="background-image: url('<%= asset_path("background_white.jpg") %>'); background-size: cover; background-position: center;">
              <div class="meta">
                <div><%= image_tag "cubes.jpg", class: "img-thumbnail"%></div>
              </div>
              <div class="card-body">
                <h4 class="card-title"> <%= consultation.name %></h1>
                <h6 class="card-subtitle mb-2 text-muted">Location:<%= consultation.address %></h2>
                <p>Tel: <%= consultation.kontakt %></p>
                <p>Email: example-email@gmail.com </p>
                <p>Website: www.this-is-example.com </p>
                <p>Opening Hours:<%= consultation.opening_hours %></p>
                <p class="read-more">
                  <a href="#">Read More</a>
                </p>
              </div>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Social Website" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="<%= consultations_index_path %>">
          <%= image_tag "logo-color.png", alt: "Brand Logo", class: "d-inline-block align-text-top rounded-circle", style: "width: 180px; height: auto;"  %>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Soziale Angebote</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Karte</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Themen
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="#" tabindex="-1" aria-disabled="true">Über uns</a>
            </li>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>